### ISSUE TITLE
how to fix after python -m demo.gradio_animate  

### ISSUE THREAD

**Issue by EKI-INDRADI** [sdbds/magic-animate-for-windows#1]
NEXT ISSUE FROM https://github.com/magic-research/magic-animate/issues/50

CUDA SDK 11.8 + ENV latest already installed
CUDA NCNN 8.9+ ENV latest already installed
FFMPEG 6 + ENV already installed

unet/config.json from https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/unet/config.json already exist

create pretrained_models
git lfs clone https://huggingface.co/zcxu-eric/MagicAnimate
git lfs clone https://huggingface.co/stabilityai/sd-vae-ft-mse
git lfs clone https://huggingface.co/runwayml/stable-diffusion-v1-5

```sh
conda create -n m_animate_for_win python=3.10 -y
conda activate m_animate_for_win
pip install -r requirements-windows.txt
python -m demo.gradio_animate  <<<< has issue
```

```sh
(m_animate_for_win) V:\_ANIMATION\MAGIC_ANIMATE\magic-animate-for-windows>python -m demo.gradio_animate
V:\_ANIMATION\MAGIC_ANIMATE\magic-animate-for-windows\magicanimate\pipelines\pipeline_animation.py:43: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
Initializing MagicAnimate Pipeline...
loaded temporal unet's pretrained weights from pretrained_models/stable-diffusion-v1-5\unet ...
### missing keys: 560;
### unexpected keys: 0;
### Temporal Module Parameters: 417.1376 M
Traceback (most recent call last):
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate_for_win\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate_for_win\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "V:\_ANIMATION\MAGIC_ANIMATE\magic-animate-for-windows\demo\gradio_animate.py", line 19, in <module>
    animator = MagicAnimate()
  File "V:\_ANIMATION\MAGIC_ANIMATE\magic-animate-for-windows\demo\animate.py", line 70, in __init__
    vae = AutoencoderKL.from_pretrained(config.pretrained_model_path, subfolder="vae")
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate_for_win\lib\site-packages\diffusers\models\modeling_utils.py", line 553, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate_for_win\lib\site-packages\diffusers\configuration_utils.py", line 364, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory pretrained_models/stable-diffusion-v1-5.
```

thanks

**Comment by EKI-INDRADI** [comment]
SOLVED https://github.com/EKI-INDRADI/magic-animate-for-windows-rnd-20231206
