### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by CGMikeG** [sdbds/magic-animate-for-windows#20]
I keep getting below error while trying to run magic-animate. Can anybody confirm if this is just a false positive.

Running on local URL:  http://127.0.0.1:7860
Traceback (most recent call last):
  File "G:\GITHUB\magic-animate-for-windows\venv\lib\site-packages\gradio\networking.py", line 232, in setup_tunnel
    address = tunnel.start_tunnel()
  File "G:\GITHUB\magic-animate-for-windows\venv\lib\site-packages\gradio\tunneling.py", line 67, in start_tunnel
    self.url = self._start_tunnel(BINARY_PATH)
  File "G:\GITHUB\magic-animate-for-windows\venv\lib\site-packages\gradio\tunneling.py", line 95, in _start_tunnel
    self.proc = subprocess.Popen(
  File "C:\Users\micha\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\micha\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\GITHUB\magic-animate-for-windows\venv\lib\site-packages\gradio\blocks.py", line 1978, in launch
    share_url = networking.setup_tunnel(
  File "G:\GITHUB\magic-animate-for-windows\venv\lib\site-packages\gradio\networking.py", line 235, in setup_tunnel
    raise RuntimeError(str(e)) from e
RuntimeError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\GITHUB\magic-animate-for-windows\demo\gradio_animate.py", line 141, in <module>
    demo.launch(share=True)
  File "G:\GITHUB\magic-animate-for-windows\venv\lib\site-packages\gradio\blocks.py", line 1996, in launch
    if Path(BINARY_PATH).exists():
  File "C:\Users\micha\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1290, in exists
    self.stat()
  File "C:\Users\micha\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software: 'G:\\GITHUB\\magic-animate-for-windows\\venv\\lib\\site-packages\\gradio\\frpc_windows_amd64_v0.2'

**Comment by sdbds** [comment]
cant reproduce this
