### ISSUE TITLE
运行后添加任何视频都显示“错误”

### ISSUE THREAD

**Issue by KadeFrank** [sdbds/magic-animate-for-windows#22]
安装运行成功，打开生成的网页后，无论添加什么视频都显示“错误”
![image](https://github.com/sdbds/magic-animate-for-windows/assets/125382994/9fd196e5-76cf-4fe7-8289-c7018372cfd0)
运行显示的代码如下（有点长）
————————————————————————————————————————
安全警告
请只运行你信任的脚本。虽然来自 Internet 的脚本会有一定的用处，但此脚本可能会损坏你的计算机。如果你信任此脚本，请使用
Unblock-File cmdlet 允许运行该脚本，而不显示此警告消息。是否要运行 E:\magic-animate-for-windows-2.1\run_gui.ps1?
[D] 不运行(D)  [R] 运行一次(R)  [S] 暂停(S)  [?] 帮助 (默认值为“D”): r
E:\magic-animate-for-windows-2.1\magicanimate\pipelines\pipeline_animation.py:43: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
Initializing MagicAnimate Pipeline...
### unexpected keys: 51;
The config attributes {'addition_embed_type': None, 'addition_embed_type_num_heads': 64, 'addition_time_embed_dim': None, 'conditioning_channels': 3, 'encoder_hid_dim': None, 'encoder_hid_dim_type': None, 'global_pool_conditions': False, 'num_attention_heads': None, 'transformer_layers_per_block': 1} were passed to ControlNetModel, but are not expected and will be ignored. Please verify your config.json configuration file.
It is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.
It is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.
It is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.
It is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.
Using Densepose ControlNet
E:\magic-animate-for-windows-2.1\magicanimate\pipelines\pipeline_animation.py:103: FutureWarning: The configuration file of this scheduler: DDIMScheduler {
  "_class_name": "DDIMScheduler",
  "_diffusers_version": "0.21.4",
  "beta_end": 0.012,
  "beta_schedule": "linear",
  "beta_start": 0.00085,
  "clip_sample": true,
  "clip_sample_range": 1.0,
  "dynamic_thresholding_ratio": 0.995,
  "num_train_timesteps": 1000,
  "prediction_type": "epsilon",
  "rescale_betas_zero_snr": false,
  "sample_max_value": 1.0,
  "set_alpha_to_one": true,
  "steps_offset": 0,
  "thresholding": false,
  "timestep_spacing": "leading",
  "trained_betas": null
}
 is outdated. `steps_offset` should be set to 1 instead of 0. Please make sure to update the config accordingly as leaving `steps_offset` might led to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull request for the `scheduler/scheduler_config.json` file
  deprecate("steps_offset!=1", "1.0.0", deprecation_message, standard_warn=False)
E:\magic-animate-for-windows-2.1\magicanimate\pipelines\pipeline_animation.py:116: FutureWarning: The configuration file of this scheduler: DDIMScheduler {
  "_class_name": "DDIMScheduler",
  "_diffusers_version": "0.21.4",
  "beta_end": 0.012,
  "beta_schedule": "linear",
  "beta_start": 0.00085,
  "clip_sample": true,
  "clip_sample_range": 1.0,
  "dynamic_thresholding_ratio": 0.995,
  "num_train_timesteps": 1000,
  "prediction_type": "epsilon",
  "rescale_betas_zero_snr": false,
  "sample_max_value": 1.0,
  "set_alpha_to_one": true,
  "steps_offset": 1,
  "thresholding": false,
  "timestep_spacing": "leading",
  "trained_betas": null
}
 has not set the configuration `clip_sample`. `clip_sample` should be set to False in the configuration file. Please make sure to update the config accordingly as not setting `clip_sample` in the config might lead to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull request for the `scheduler/scheduler_config.json` file
  deprecate("clip_sample not set", "1.0.0", deprecation_message, standard_warn=False)
Initialization Done!
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://aa63f8e33c20cd50dd.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Traceback (most recent call last):
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\blocks.py", line 1520, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\blocks.py", line 1303, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\components\video.py", line 168, in preprocess
    duration = processing_utils.get_video_length(file_name)
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\processing_utils.py", line 725, in get_video_length
    duration = subprocess.check_output(
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\blocks.py", line 1520, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\blocks.py", line 1303, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\components\video.py", line 168, in preprocess
    duration = processing_utils.get_video_length(file_name)
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\processing_utils.py", line 725, in get_video_length
    duration = subprocess.check_output(
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

**Comment by KadeFrank** [comment]
补充一下，自带的例子提交后的结果也显示“错误”
![image](https://github.com/sdbds/magic-animate-for-windows/assets/125382994/e18e6d38-c2c6-4787-937e-a389c551e850)

**Comment by KadeFrank** [comment]
补充一下，添加视频后，显示“错误”，命令行中的错误信息如下（有点长）
——————————————————————————
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Traceback (most recent call last):
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\blocks.py", line 1520, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\blocks.py", line 1303, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\components\video.py", line 168, in preprocess
    duration = processing_utils.get_video_length(file_name)
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\processing_utils.py", line 725, in get_video_length
    duration = subprocess.check_output(
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\blocks.py", line 1520, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\blocks.py", line 1303, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\components\video.py", line 168, in preprocess
    duration = processing_utils.get_video_length(file_name)
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\processing_utils.py", line 725, in get_video_length
    duration = subprocess.check_output(
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\CJZ\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "E:\magic-animate-for-windows-2.1\venv\lib\site-packages\gradio\queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

**Comment by sdbds** [comment]
控制台输入一下Set-ExecutionPolicy Unrestricted打开脚本权限

**Comment by KadeFrank** [comment]
> 控制台输入一下Set-ExecutionPolicy Unrestricted打开脚本权限

感谢xd，等下班回家再试试

**Comment by KadeFrank** [comment]
找到问题了，是ffmpeg的文件夹没改名为“ffmpeg”，改完就能运行了。但是我的显卡配置太低(GTX 1060 6G)，跑了半个小时还是0%，宣告放弃...
————————————————————————————
E:\magic-animate-for-windows\magicanimate\pipelines\pipeline_animation.py:624: FutureWarning: Accessing config attribute `in_channels` directly via 'UNet3DConditionModel' object attribute is deprecated. Please access 'in_channels' over 'UNet3DConditionModel's config object instead, e.g. 'unet.config.in_channels'.
  num_channels_latents = self.unet.in_channels
  0%|                                                                                           | 0/25 [00:00<?, ?it/s]

**Comment by Mo01iHt** [comment]
我也遇到这个问题，似乎和显卡配置无关，我是RTX 3050，一直保持在  0%|                                                                                   | 0/25 [00:00<?, ?it/s]
如果是配置太低，至少应该会跑动，并且有预计时间，而不是问好？。我正在找解决方案，如果您解决了这个问题，请您同样分享给我！
