### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers.pipeline_utils'

### ISSUE THREAD

**Issue by Augus202312** [sdbds/magic-animate-for-windows#3]
`(animate) PS F:\code\magic-animate-for-windows> python -m demo.gradio_animate
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\animate\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramData\Anaconda3\envs\animate\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\code\magic-animate-for-windows\demo\gradio_animate.py", line 17, in <module>
    from demo.animate import MagicAnimate
  File "F:\code\magic-animate-for-windows\demo\animate.py", line 33, in <module>
    from magicanimate.pipelines.pipeline_animation import AnimationPipeline
  File "F:\code\magic-animate-for-windows\magicanimate\pipelines\pipeline_animation.py", line 43, in <module>
    from diffusers.pipeline_utils import DiffusionPipeline
ModuleNotFoundError: No module named 'diffusers.pipeline_utils'`
![image](https://github.com/sdbds/magic-animate-for-windows/assets/153266602/18b411e0-a39e-45d9-a8ee-9919535286b5)

**Comment by FurkanGozukara** [comment]
i have got windows auto installer that uses pip and venv : https://github.com/magic-research/magic-animate/issues/44

**Comment by sdbds** [comment]
> `(animate) PS F:\code\magic-animate-for-windows> python -m demo.gradio_animate Traceback (most recent call last): File "D:\ProgramData\Anaconda3\envs\animate\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "D:\ProgramData\Anaconda3\envs\animate\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "F:\code\magic-animate-for-windows\demo\gradio_animate.py", line 17, in <module> from demo.animate import MagicAnimate File "F:\code\magic-animate-for-windows\demo\animate.py", line 33, in <module> from magicanimate.pipelines.pipeline_animation import AnimationPipeline File "F:\code\magic-animate-for-windows\magicanimate\pipelines\pipeline_animation.py", line 43, in <module> from diffusers.pipeline_utils import DiffusionPipeline ModuleNotFoundError: No module named 'diffusers.pipeline_utils'` ![image](https://private-user-images.githubusercontent.com/153266602/288996278-18b411e0-a39e-45d9-a8ee-9919535286b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNDMxMjQsIm5iZiI6MTcwMjE0MjgyNCwicGF0aCI6Ii8xNTMyNjY2MDIvMjg4OTk2Mjc4LTE4YjQxMWUwLWEzOWUtNDVkOS1hOGVlLTk5MTk1MzUyODZiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxNzI3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDQzMzVkMmI5NzZlNWIzNjc4NTc4MTM3NTI2MGJjNmY0MDFlNmRmMWRiOTY0YzEyNmVkYjg1MmYxNWU3MjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3LeEEkDZlAy-AKo1aG3rEwulr-UcpkLeE3dhHYA_tZo)

you model have not downloaded or lack of depends
